---
- name: get playbook dir
  ansible.builtin.debug:
    var: playbook_dir

- name: get role_path dir
  ansible.builtin.debug:
    var: role_path

- name: replace stig module config
  ansible.builtin.copy:
    src: config.yml
    dest: "{{ playbook_dir }}/../roles-galaxy/mindpointgroup.stig_rhel6/tasks/main.yml"
    force: yes
