- name: check linux os
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_distribution == 'RedHat'

- name: check windows os
  ansible.builtin.include_tasks: windows.yml
  when: "'Microsoft Windows Server' in ansible_distribution"
