---
# Avoid re-installing everytime this role is called by doing a HEAD request
# on the URL and only triggering the install if Last Modified has changed

- name: Retrieve awscli zip stats
  ansible.builtin.uri:
    method: "HEAD"
    url: "{{ awscli_installer_url }}"
  check_mode: no
  register: awscli_zip

- name: Write awscli zip stats
  ansible.builtin.template:
    src: .ansible-amazon-cli.txt.j2
    dest: "~/.ansible-amazon-cli.txt"
  notify:
    - Install aws cli
