---
- name: Retrieve awscli zip stats
  ansible.builtin.uri:
    method: "HEAD"
    url: "{{ awscli_installer_url }}"
  check_mode: no
  register: awscli_zip

- name: Write awscli zip stats 
  ansible.builtin.template:
    src: .ansible-amazon-cli.txt.j2
    dest: "~/.ansible-amazon-cli.txt"
  notify:
    - Install aws cli
