- name: install ASM packages
  ansible.builtin.yum:
    name: kmod-oracleasm # note, 2 other required packages are installed as part of pre_install_tasks.yml
    state: present
    enablerepo: rhel-7-server-rhui-optional-rpms

- name: configure ASMlib
  ansible.builtin.command: oracleasm configure --user oracle --group oinstall --enable --scanboot y

- name: initialise ASMlib
  ansible.builtin.command: oracleasm init

- name: partition disk
  community.general.parted:
    device: "{{ drive_map[item.device] }}"
    number: 1
    part_type: primary
    state: present
  loop: "{{ oracle_asm_data_disks + oracle_asm_flash_disks }}"

- name: check for existing ASM disks
  ansible.builtin.command: oracleasm listdisks
  register: asm_disks

- name: create ASM disk
  ansible.builtin.command: oracleasm createdisk {{ item.label | quote }} {{ drive_map[item.device] | quote }}p1
  loop: "{{ oracle_asm_data_disks + oracle_asm_flash_disks }}"
  when: item.label not in asm_disks.stdout_lines

- name: verify ASM disks
  ansible.builtin.command: oracleasm listdisks
  register: asm_disks # used in grid_install.rsp.j2 template

- name: assert ASM disks all there
  ansible.builtin.assert:
    that: "{{ (oracle_asm_data_disks + oracle_asm_flash_disks) | json_query('[*].label') | difference(asm_disks.stdout_lines) | length == 0 }}"
    fail_msg: "some ASM disks were not successfully created"
