# Systemd script-exporter service is run as a prometheus user

- name: check prometheus user exists
  ansible.builtin.getent:
    database: passwd
    key: prometheus

- name: add sudo privileges for running oracle health checks
  ansible.builtin.copy:
    content: "prometheus ALL = (oracle) NOPASSWD: /bin/bash -c /opt/script-exporter/*.sh\n"
    dest: /etc/sudoers.d/prometheus
    owner: root
    group: root
    mode: 0644

- name: get script_exporter archive
  ansible.builtin.unarchive:
    src: "https://github.com/adhocteam/script_exporter/releases/download/v{{ script_exporter_version }}/script_exporter-{{ script_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    list_files: yes
  register: archive_contents

- name: copy the binary into /usr/bin
  ansible.builtin.copy:
    src: "/tmp/{{ archive_contents.files[0] }}script_exporter"
    dest: /usr/bin/script-exporter
    owner: prometheus
    group: root
    mode: 0500

- name: clean up files
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - "{{ archive_contents.files[0].split('/')[0] }}.tar.gz"
    - "{{ archive_contents.files[0].split('/')[0] }}"

- name: install systemd unit
  ansible.builtin.copy:
    src: script-exporter.service
    dest: /etc/systemd/system/script-exporter.service
    owner: root
    group: root
    mode: 0644
  notify: reload script-exporter

- name: create script exporter config directory
  ansible.builtin.file:
    path: /opt/script-exporter
    state: directory
    owner: prometheus
    group: root
    mode: 0755

- name: install environment variables for systemd unit
  ansible.builtin.copy:
    src: script-exporter.env
    dest: /opt/script-exporter/script-exporter.env
    owner: prometheus
    group: root
    mode: 0400
  notify: reload script-exporter

- name: create config file
  ansible.builtin.file:
    path: /opt/script-exporter/config.yml
    state: touch
    owner: prometheus
    group: root
    mode: 0400

- name: start & enable service
  ansible.builtin.service:
    name: script-exporter
    state: started
    enabled: yes
