---
name: #TEAM#_#SUFFIX#
on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - "teams/#TEAM#/**"
      - ".github/workflows/#TEAM#_#SUFFIX#.yml"
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - "teams/#TEAM#/**"
      - ".github/workflows/#TEAM#_#SUFFIX#.yml"
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true
  MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
  PASSPHRASE: ${{ secrets.PASSPHRASE }}

permissions: {}

jobs:
  fetch-secrets:
    uses: ministryofjustice/modernisation-platform-github-actions/.github/workflows/aws-secrets-management.yml@7b8dd97eb5b596a88206805943771ea7ffcde235 # v3.4.8
    permissions:
      id-token: write
      contents: read
    secrets:
      MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}

  plan-#TEAM#_#SUFFIX#:
    name: Plan - #TEAM#_#SUFFIX# pipelines
    runs-on: ubuntu-latest
    needs: fetch-secrets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Decrypt Secrets
        uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@7b8dd97eb5b596a88206805943771ea7ffcde235 # v3.4.8
        with:
          testing_ci_iam_user_access_key_id: ${{ needs.fetch-secrets.outputs.testing_ci_iam_user_access_key_id }}
          testing_ci_iam_user_secret_access_key: ${{ needs.fetch-secrets.outputs.testing_ci_iam_user_secret_access_key }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform plan - #TEAM#_#SUFFIX# pipelines
        run: |
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh teams/#TEAM#
          terraform -chdir="teams/#TEAM#" workspace select "core-shared-services-${TF_ENV}"
          bash scripts/terraform-plan.sh teams/#TEAM#
        env:
          TF_ENV: production

  deploy-#TEAM#_#SUFFIX#:
    name: Deploy - #TEAM#_#SUFFIX# pipelines
    needs: [fetch-secrets, plan-#TEAM#_#SUFFIX#]
    runs-on: ubuntu-latest
    environment:
      name: core-shared-services
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Decrypt Secrets
        uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@7b8dd97eb5b596a88206805943771ea7ffcde235 # v3.4.8
        with:
          testing_ci_iam_user_access_key_id: ${{ needs.fetch-secrets.outputs.testing_ci_iam_user_access_key_id }}
          testing_ci_iam_user_secret_access_key: ${{ needs.fetch-secrets.outputs.testing_ci_iam_user_secret_access_key }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform apply - #TEAM#_#SUFFIX# pipelines
        run: |
          echo "Terraform apply - ${TF_ENV}"
          bash scripts/terraform-init.sh teams/#TEAM#
          terraform -chdir="teams/#TEAM#" workspace select "core-shared-services-${TF_ENV}"
          bash scripts/terraform-apply.sh teams/#TEAM#
        env:
          TF_ENV: production