---
- name: Packages Playbook
  hosts: 127.0.0.1
  become: yes
  connection: local
  gather_facts: false
  tasks:
    - name: install common packages
      ansible.builtin.yum:
        name:
          - zip
          - unzip
          - wget
          - gcc
          - screen # for AWS Session Manager logging
        state: present
        update_cache: yes
        enablerepo: rhel-7-server-rhui-extras-rpms