---
name: base

on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'One or more project to plan/apply, space separated'
        required: true
        default: ''
      action:
        description: 'Set to plan or apply'
        required: true
        default: 'plan'

  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - commonimages/base/**
      - modules/imagebuilder/**
      - .github/workflows/base.yml
      - ansible/**

  push:
    branches:
      - main
    paths:
      - commonimages/base/**
      - modules/imagebuilder/**
      - .github/workflows/base.yml
      - ansible/**

permissions:
  contents: read # This is required for actions/checkout
  id-token: write # This is required for requesting the JWT
  issues: write # Required for posting comments on PRs
  pull-requests: write # For posting comments to PR

defaults:
  run:
    shell: bash

jobs:
  base-plan-apply:
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      team_dir: commonimages/base
      projects: ${{ github.event.inputs.projects }}
      action: ${{ github.event.inputs.action }}
    secrets:
      MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}