---
name: delius-iaps

on:
  workflow_dispatch:
    inputs:
      projects:
        description: "One or more project to plan/apply, space separated"
        required: true
        default: ""
      action:
        description: "Set to plan or apply"
        required: true
        default: "plan"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - teams/delius-iaps/**
      - modules/imagebuilder/**
      - .github/workflows/delius-iaps.yml
      - ansible/**

  push:
    branches:
      - main
    paths:
      - teams/delius-iaps/**
      - modules/imagebuilder/**
      - .github/workflows/delius-iaps.yml
      - ansible/**

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # For posting comments to PR

defaults:
  run:
    shell: bash

jobs:
  delius-iaps-plan-apply:
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      team_dir: teams/delius-iaps
      projects: ${{ github.event.inputs.projects }}
      action: ${{ github.event.inputs.action }}
    secrets:
      MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}