---
name: example
on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'teams/example/**'
      - '.github/workflows/example.yml'
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'teams/example/**'
      - '.github/workflows/example.yml'
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # For posting comments to PR
  issues: write # Required for posting comments on PRs

defaults:
  run:
    shell: bash

jobs:
  example-plan-apply:
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      team_dir: teams/example
      projects: ${{ github.event.inputs.projects }}
      action: ${{ github.event.inputs.action }}
    secrets:
      MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}