---
name: example
on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'teams/example/**'
      - '.github/workflows/example.yml'
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'teams/example/**'
      - '.github/workflows/example.yml'
  workflow_dispatch:
env:
  AWS_REGION: "eu-west-2"
  ENVIRONMENT_MANAGEMENT: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}
  TF_IN_AUTOMATION: true
defaults:
  run:
    shell: bash

permissions: {}

jobs:
  plan-example:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    name: Plan - example pipelines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Set Account Number
        run: echo "ACCOUNT_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< $ENVIRONMENT_MANAGEMENT)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@5727f247b64f324ec403ac56ae05e220fd02b65f # v2.1.0
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform plan - example pipelines
        run: |
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh teams/example
          terraform -chdir="teams/example" workspace select "core-shared-services-${TF_ENV}"
          bash scripts/terraform-plan.sh teams/example
        env:
          TF_ENV: production

  deploy-example:
    name: Deploy - example pipelines
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    needs: plan-example
    runs-on: ubuntu-latest
    environment:
      name: core-shared-services
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Set Account Number
        run: echo "ACCOUNT_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< $ENVIRONMENT_MANAGEMENT)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@5727f247b64f324ec403ac56ae05e220fd02b65f # v2.1.0
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform apply - example pipelines
        run: |
          echo "Terraform apply - ${TF_ENV}"
          bash scripts/terraform-init.sh teams/example
          terraform -chdir="teams/example" workspace select "core-shared-services-${TF_ENV}"
          bash scripts/terraform-apply.sh teams/example
        env:
          TF_ENV: production
