---
name: nomis
on:
  # push:
  #   branches:
  #     - nomis/*
  #   paths:
  #     - 'teams/nomis/**'
  #     - '.github/workflows/nomis.yml'
  #     - '!teams/nomis/pipelines/**'

  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'teams/nomis/**'
      - '.github/workflows/nomis.yml'
      - '!teams/nomis/pipelines/jumpserver/**'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
  TF_VAR_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  TF_VAR_GH_ACTOR_NAME: ${{ github.actor}}
defaults:
  run:
    shell: bash

jobs:
  plan-nomis:
    name: Plan - nomis pipelines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform plan - nomis pipelines
        run: |
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh teams/nomis
          terraform -chdir="teams/nomis" workspace select "core-shared-services-${TF_ENV}"
          bash scripts/terraform-plan.sh teams/nomis
        env:
          TF_ENV: production

  deploy-nomis:
    name: Deploy - nomis pipelines
    needs: plan-nomis
    runs-on: ubuntu-latest
    environment:
      name: core-shared-services
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform apply - nomis pipelines
        run: |
          echo "Terraform apply - ${TF_ENV}"
          bash scripts/terraform-init.sh teams/nomis
          terraform -chdir="teams/nomis" workspace select "core-shared-services-${TF_ENV}"
          bash scripts/terraform-apply.sh teams/nomis
        env:
          TF_ENV: production
