name: Terraform Static Code Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - 'modernisation-platform/**'
      - 'teams/team1/**'
      - '.github/workflows/terraform-static-analysis.yml'

jobs:
  terraform-static-analysis:
    name: Terraform Static Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0
    - name: Run Analysis
      uses: ministryofjustice/github-actions/terraform-static-analysis@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        scan_type: changed
        checkov_exclude: CKV_AWS_180
        tflint_exclude: terraform_unused_declarations,terraform_required_version

  terraform-static-analysis-full-scan:
    name: Terraform Static Analysis - scan all directories
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0
    - name: Run Analysis
      uses: ministryofjustice/github-actions/terraform-static-analysis@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        scan_type: full
        tflint_exclude: terraform_unused_declarations,terraform_required_version
